### ISSUE TITLE
Improvements for new Animal Dialog

### ISSUE THREAD

**Issue by splitbrain** [micgro42/dokuwiki-plugin-farmer#3]
See screenshot:

![farmer1](https://cloud.githubusercontent.com/assets/86426/9436381/0f0a71a4-4a4f-11e5-9c0e-2163d5f70547.png)

**Comment by splitbrain** [comment]
![farmer3](https://cloud.githubusercontent.com/assets/86426/9436779/1d07ccd6-4a52-11e5-9163-ba23ca9cf005.png)

**Comment by splitbrain** [comment]
![farmer4](https://cloud.githubusercontent.com/assets/86426/9437138/c5885cd4-4a54-11e5-91f9-12568d37fe2e.png)

**Comment by micgro42** [comment]
done
