### ISSUE TITLE
Edit Animal Improvements

### ISSUE THREAD

**Issue by splitbrain** [micgro42/dokuwiki-plugin-farmer#5]
See screenshot

![farmer2](https://cloud.githubusercontent.com/assets/86426/9436496/1871b652-4a50-11e5-840b-ad28c30e7bcc.png)

**Comment by splitbrain** [comment]
![farmer5](https://cloud.githubusercontent.com/assets/86426/9437369/3eacdc74-4a56-11e5-8e2f-458b663d4d68.png)

**Comment by micgro42** [comment]
done
